remote_theme: LeNPaul/Millennial
  # daviddarnes/garth Current
  # daviddarnes/alembic@main 
  # jekyll-theme-basically-basic

plugins: 
- jekyll-remote-theme


title: Bengali Fish Recognizer

author:
  name: Neloy Barman

