remote_theme: onwidget/astrowind 
  # daviddarnes/garth
  # daviddarnes/alembic@main 
  # jekyll-theme-basically-basic

plugins: 
- jekyll-remote-theme


title: Bengali Fish Recognizer

author:
  name: Neloy Barman

